apiVersion: gitops.kpt.dev/v1alpha1
kind: Rollout
metadata:
  name: fleet-namespace-rollout
spec:
  description: rollout namespaces to all the stores
  clusters:
    sourceType: GCPFleet
    gcpFleet:
      projectIds:
      - sunilarora-sandbox
  packages:
    sourceType: GitHub
    github:
      selector:
        org: droot
        repo: store
        directory: namespaces
        revision: v3
        secretRef:
          name: github-rollout-token
  packageToTargetMatcher:
    type: AllClusters
  targets:
    selector:
      matchExpressions:
        - {key: state, operator: In, values: [ga, ny, ca]}
  strategy:
    type: Progressive
    progressive:
      namespace: default
      name: stores-rollout-strategy
      pauseAfterWave:
        waveName: GA-stores
