apiVersion: gitops.kpt.dev/v1alpha1
kind: Rollout
metadata:
  name: fleet-mecho-app-rollout
spec:
  description: Rollout mecho app to all the stores
  clusters:
    sourceType: GCPFleet
    gcpFleet:
      projectIds:
      - sunilarora-sandbox
  targets:
    selector:
      matchLabels:
        env: dev
  packages:
    sourceType: GitHub
    github:
      selector:
        org: droot
        repo: "store-*"
        directory: echo
        revision: v1
  packageToTargetMatcher:
    type: Custom
    matchExpression: rolloutPackage.repo == 'store-1'
  syncTemplate:
    type: RootSync
    rootSync:
      sourceFormat: unstructured
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxConcurrent: 3
