apiVersion: gitops.kpt.dev/v1alpha1
kind: Rollout
metadata:
  name: gl-namespace-rollout
spec:
  description: namespace rollout
  clusters:
    sourceType: GCPFleet
    gcpFleet:
      projectIds:
      - sunilarora-sandbox
  packages:
    sourceType: GitLab
    gitlab:
      secretRef:
        name: gitlab-token
      selector:
        projectID: "19466078"
        directory: namespaces
        branch: "master"
  packageToTargetMatcher:
    type: AllClusters
  targets:
    selector:
      matchLabels:
        state: ga
  syncTemplate:
    type: RootSync
    rootSync:
      sourceFormat: unstructured
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxConcurrent: 2
