apiVersion: gitops.kpt.dev/v1alpha1
kind: Rollout
metadata:
  name: namespace-rollout
spec:
  description: Rollout namespaces to a set of clusters
  clusters:
    sourceType: KCC
  packages:
    sourceType: GitHub
    github:
      selector:
        org: droot
        repo: kpt-packages
        directory: namespaces
        revision: main
  targets:
    selector:
      matchLabels:
        location: us-west1
  #      matchExpressions:
  #      - {key: env, operator: In, values: [dev, staging]}
  packageToTargetMatcher:
    type: AllClusters
  strategy:
    type: Progressive
    progressive:
      namespace: default
      name: default-rollout-strategy
      pauseAfterWave:
        waveName: dev-clusters
