apiVersion: gitops.kpt.dev/v1alpha1
kind: Rollout
metadata:
  name: stores-namespace-rollout
spec:
  description: Rollout namespaces to all the stores
  packages:
    sourceType: GitHub
    github:
      selector:
        org: droot
        repo: store
        directory: namespaces
        revision: v2
  targets:
    selector:
      matchExpressions:
        - {key: location/state, operator: In, values: [GA, NY, CA]}
  packageToTargetMatcher:
    type: AllClusters
  strategy:
    type: Progressive
    progressive:
      namespace: default
      name: stores-rollout-strategy
      pauseAfterWave:
        waveName: GA-stores
