apiVersion: gitops.kpt.dev/v1alpha1
kind: Rollout
metadata:
  name: stores-mecho-app-rollout
spec:
  description: Rollout kecho app to all the stores
  clusters:
    sourceType: KCC
  targets:
    selector:
      matchExpressions:
        - {key: location/state, operator: In, values: [GA, NY, CA]}
  packages:
    sourceType: GitHub
    github:
      selector:
        org: droot
        repo: "store-*"
        directory: echo
        revision: v1
  packageToTargetMatcher:
    type: Custom
    matchExpression: rolloutPackage.repo == cluster.name
  syncTemplate:
    type: RootSync
    rootSync:
      sourceFormat: unstructured
  strategy:
    type: Progressive
    progressive:
      namespace: default
      name: stores-rollout-strategy
      pauseAfterWave:
        waveName: GA-stores
