apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata: # kpt-merge: config-control/example
  name: store-2
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn-live'
    internal.kpt.dev/upstream-identifier: 'container.cnrm.cloud.google.com|ContainerCluster|config-control|example'
  labels:
    location/country: USA
    location/state: CA
    location/city: SF
spec:
  description: store-2
  initialNodeCount: 3
  location: us-west1
  releaseChannel:
    channel: REGULAR
